header:
  license:
    spdx-id: EPL-2.0
    copyright-owner: Contributors to the Eclipse Foundation
    content: |
      Copyright (c) 2022 Contributors to the Eclipse Foundation.
      
      This program and the accompanying materials are made
      available under the terms of the Eclipse Public License 2.0
      which is available at https://www.eclipse.org/legal/epl-2.0/
      SPDX-License-Identifier: EPL-2.0
      
      Contributors:

    pattern: |
      This program and the accompanying materials are made
      available under the terms of the Eclipse Public License 2.0
      which is available at https://www.eclipse.org/legal/epl-2.0/
      \|
      This software is subject to the terms of the Eclipse Public License v1.0
      Agreement, available at the following URL:
      http://www.eclipse.org/legal/epl-v10.html.
      You must accept the terms of that agreement to use this software.

  paths-ignore:
    - 'dist'
    - 'LICENSE.txt'
    - 'licenses'
    - '**/package-info.java'
    - '**/packageinfo'
    - '**/module-info.java'
    - '**/*.bnd'
    - '**/*.csv'
    - '**/*.bndrun'
    - '**/*.xml'
    - '**/*.ecore'
    - '**/*.genmodel'
    - '**/*.md'
    - '**/*.MD'
    - '**/.keep'
    - '**/*.jetproperties'
    - '**/*.javajet'
    - '**/*.javajetinc'
    - '**/*.json'
    - '**/*.properties'
    - '**/*.maven'
    - '**/*.html'
    - '**/*.aird'
    - '**/*.basic'
    - '**/.classpath'
    - '**/.editorconfig'
    - 'legacy/**'
    - 'LICENSE'
    - 'NOTICE'
    - '.gitattributes'
    - '.github/**'
    - '.gitignore'
    - '.licenserc.yaml'
    - '**/.project'
    - '**/*.prefs'
    - 'license.templates'
    - 'mondrian/src/it/**'
    - 'prototype/distribution/launcher/src/test/resources/repository/**'
 
  comment: always
