/*
 * Project version information. Generated - do not modify.
 */
package mondrian.server;
/**
 * Version information for Mondrian. (Generated by build)
 */
//WAS AUTO GENERATED. JUST COPIED . TO BE REMOVED

class MondrianServerVersion {
    static final String VENDOR = "opencube.org";
    static final String NAME = "org.eclipse.daanse.emondrian";
    static final String VERSION = "0.0.1-SNAPSHOT";
    static final int MAJOR_VERSION = 8;
    static final int MINOR_VERSION = 000;
    static final int SCHEMA_VERSION = 3;
    static final String COPYRIGHT_YEAR = "${copyright.year}";
}
// End MondrianServerVersion.java